apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels: 
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: mypod-pod
      labels:
        app: mypod
        type: back-end
    spec:
      containers:
      - name: nginx-container
        image: nginx 
  replicas: 3