From node:12-stretch 

USER node

WORKDIR /home/node/code

COPY --chown=node:node index.js index.js
#these two lines are doing the same thing right now. 
#copy does less, add is more powerful.
ADD --chown=user:group index.js index.js

CMD [ "node", "index.js" ]